version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-container
    env_file:
      - /root/fastapi/.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5432}:5432"
    deploy:
      resources:
        limits:
          memory: 150m
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend_net

  redis:
    image: redis:7-alpine
    container_name: redis-container
    volumes:
      - redis_data:/var/lib/redis/data
    command: >
      redis-server
      --requirepass ${REDIS_PASS}
      --bind 0.0.0.0
      --maxmemory 80mb
      --maxmemory-policy allkeys-lru
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    deploy:
      resources:
        limits:
          memory: 100m
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASS}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend_net

  fastapi:
    image: asdfrewqha/:latest
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    container_name: fastapi-container
    env_file:
      - /root/fastapi/.env
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    expose:
      - 8000
    networks:
      - nginx_net
      - backend_net

  aiobot:
    image: asdfrewqha/:latest
    command: python bot.py
    container_name: aiobot-container
    env_file:
      - /root/fastapi/.env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend_net
    restart: always

  scheduler:
    image: asdfrewqha/:latest
    command: taskiq scheduler app.core.taskiq.broker:scheduler
    container_name: scheduler-container
    env_file:
      - /root/fastapi/.env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend_net
    restart: always

  taskiq:
    image: asdfrewqha/:latest
    command: taskiq worker app.core.taskiq.broker:broker app.core.taskiq.tasks
    container_name: taskiq-container
    env_file:
      - /root/fastapi/.env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend_net
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/fastapi/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - fastapi
    restart: unless-stopped
    networks:
      - nginx_net
      - backend_net

networks:
  nginx_net:
    driver: bridge
  backend_net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
